### ISSUE TITLE
Peer Certificate Mismatch on Package Install

### ISSUE THREAD

**Issue by timkite** [wp-cli/package-command#74]
All package install attempts on RHEL6 (PHP 5.3.3) and RHEL7 (PHP 5.4.16) systems fail with:

```
Error: The "https://wp-cli.org/package-index/packages.json" file could not be downloaded: Peer certificate CN=`ssl391970.cloudflaressl.com' did not match expected CN=`wp-cli.org'
failed to open stream: HTTP request failed!
```

The command succeeds on macOS 10.13.3 (PHP 7.1.7). A direct command line curl of `https://wp-cli.org/package-index/packages.json` from the RHEL servers is successful, so the CN verification seems to be something specific being done in PHP curl. Any thoughts at a workaround?

**Comment by schlessera** [comment]
@timkite Often times, errors like these are due to outdated root certificates bundled with your curl package/extension. You'll need to update these.

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support
